### PR TITLE
A translation to Chinese made by a layman in geology.

### PR DESCRIPTION
**Pull request by PilyziFox**
I hade try as I can, but I still wonder about the mean of text in the following:
  "material.immersive_geology.refractory": "Refractory",
  "material.immersive_geology.viking_steel": "Ashbone Steel",
  "material.immersive_geology.phlebotinum": "Phlebotinum",
  "material.immersive_geology.unobtania": "unobtania".
Can someone explain to me? :)

### CODE REVIEW

**Comment by muddykat-tech** [comment]
Ashbone Steel is a primitive type of Steel that was made using bones of humans and or animals.

The people who thought that doing so would give the iron the strength of the donator of said bones.

Phlebodium is a word to describe a plot device essentially phlebotinum is used as a catch-all for pseudoscientific jargon, for example kryptonite is a type of phlebotinum as phlebotinum does whatever the author needs it to do.

Unobtainium / Unobtania is similar to phlebotinum except it's just a metal variant instead of a crystal. Examples of this in media is vibrainium the substance that Captain America's shield was made from.

We used the name unobtainium which was also used in the movie Avatar, it is essentially a perfect metal.

Refractory is a part of the refractory brick and other derivatives it's kept separate due to how the system functions.

Refractory is just a word used to describe something resistant to heat and hard to melt.

I hope that helps!

**Comment by NightmareTwilight** [comment]
Actually, Refractory refers to refraction, that is, how light bounces off and splits apart. This is used to diffuse and reflect the heat inside the furnace, bouncing it back in and spreading it evenly.

**Comment by muddykat-tech** [comment]
> Actually, Refractory refers to refraction, that is, how light bounces off and splits apart. This is used to diffuse and reflect the heat inside the furnace, bouncing it back in and spreading it evenly.

It has multiple meanings, see here:
refractory
rĭ-frăk′tə-rē
adjective

Showing or characterized by obstinate resistance to authority or control.
Difficult to melt or work; resistant to heat.
Resistant to treatment.

You were thinking of refraction, which is not the same as refractory

**Comment by PilyziFox** [comment]
> Ashbone Steel is a primitive type of Steel that was made using bones of humans and or animals.
> 
> The people who thought that doing so would give the iron the strength of the donator of said bones.
> 
> Phlebodium is a word to describe a plot device essentially phlebotinum is used as a catch-all for pseudoscientific jargon, for example kryptonite is a type of phlebotinum as phlebotinum does whatever the author needs it to do.
> 
> Unobtainium / Unobtania is similar to phlebotinum except it's just a metal variant instead of a crystal. Examples of this in media is vibrainium the substance that Captain America's shield was made from.
> 
> We used the name unobtainium which was also used in the movie Avatar, it is essentially a perfect metal.
> 
> Refractory is a part of the refractory brick and other derivatives it's kept separate due to how the system functions.
> 
> Refractory is just a word used to describe something resistant to heat and hard to melt.
> 
> I hope that helps!

yeah! things have been figured out. thx

**Pull request closed without merging**
